volumes:
  database: {}
services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        WP_DB_NAME:           ${WP_DB_NAME}
        MYSQL_USER:           ${MYSQL_USER}
        MYSQL_PASSWORD:       ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    restart: always
    expose:
      - "3306"
    networks:
      - inception
    env_file:
      - .env
    environment:
      WP_DB_NAME:             ${WP_DB_NAME}
      MYSQL_USER:             ${MYSQL_USER}
      MYSQL_PASSWORD:         ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD:    ${MYSQL_ROOT_PASSWORD}
    tty: true
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "8080:80"
      # - "443:443"
    networks:
      - inception
    tty: true
  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress
  #   restart: always
  #   volumes:
  #     - wordpress:/var/www/html
  #   ports:
  #     - 9000:9000
  #   networks:
  #     - inception
  #   depends_on:
  #     - mariadb
  #   env_file:
  #     - .env
  #   tty: true
  # adminer:
    # build: ./requirements/adminer
    # restart: always
    # ports:
    #   - 1664:80
  test:
    image: alpine
    restart: always
    tty: true

networks:
  inception:
    driver: bridge
