version: '3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        WP_DB_NAME:           ${WP_DB_NAME}
        MYSQL_USER:           ${MYSQL_USER}
        MYSQL_PASSWORD:       ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    restart: always
    expose:
      - "3306"
    networks:
      - database
    env_file:
      - .env
    environment:
      WP_DB_NAME:             ${WP_DB_NAME}
      MYSQL_USER:             ${MYSQL_USER}
      MYSQL_PASSWORD:         ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD:    ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql/
    tty: true
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "8080:80"
      # - "443:443"
    networks:
      - nginx_bridge
    tty: true
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      target: InceptionWordpress
    restart: always
    volumes:
      - wordpress_files:/var/www
    expose:
      - 9000
    networks:
      - database
      - nginx_bridge
    depends_on:
      - mariadb
    env_file:
      - .env
    tty: true
  wpcli:
    container_name: wpcli
    build:
      context: requirements/wordpress
      target: InceptionWPCli
    restart: 'no'
    depends_on:
      - wordpress
      - mariadb
    env_file:
      - .env
    volumes_from:
      - wordpress
    networks:
      - database
    entrypoint: sh /scripts/entry-point.sh
  # adminer:
  #   build: ./requirements/adminer
  #   restart: always
  #   ports:
  #     - 1664:80
  # test:
  #   image: alpine
  #   restart: always
  #   tty: true

networks:
  database:
  nginx_bridge:

volumes:
  mariadb_data:
  wordpress_files: