kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/address-pool: metallb-ip-range
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: ssh
      port: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-img
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          - name: ssh
            containerPort: 22
      restartPolicy: Always
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: nginx-job
#   labels:
#     jobgroup: nginx-job
# spec:
#   template:
#     metadata:
#       name: nginx-job
#       labels:
#         jobgroup: nginx-job
#     spec:
#       containers:
#       - name: nginx
#         image: nginx-img
#         command: ["sh", "-c", "echo Processing item && sleep 5"]
#       restartPolicy: Never
